groups:

- name: NodeExporter

  rules:
    - alert: ZfsOfflinePool
      expr: 'node_zfs_zpool_state{state!="online"} > 0'
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: ZFS offline pool (instance {{ $labels.instance }})
        description: "A ZFS zpool is in a unexpected state: {{ $labels.state }}.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: ZfsPoolOutOfSpace
      expr: zfs_pool_free_bytes * 100 / zfs_pool_size_bytes < 10 and ON (instance, device, mountpoint) zfs_pool_readonly == 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: ZFS pool out of space (instance {{ $labels.instance }})
        description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    # 0: ONLINE
    # 1: DEGRADED
    # 2: FAULTED
    # 3: OFFLINE
    # 4: UNAVAIL
    # 5: REMOVED
    # 6: SUSPENDED
    - alert: ZfsPoolUnhealthy
      expr: zfs_pool_health > 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: ZFS pool unhealthy (instance {{ $labels.instance }})
        description: "ZFS pool state is {{ $value }}. See comments for more information.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: ZfsCollectorFailed
      expr: zfs_scrape_collector_success != 1
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: ZFS collector failed (instance {{ $labels.instance }})
        description: "ZFS collector for {{ $labels.instance }} has failed to collect information\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
