keys:
  - &machine_xps15 age1uqfc83ppdychx7lnauqfg6656m6ecy72392jm3slyeal8ppw55lqe59lst
  - &machine_fury age1mqva7u3g57hjz9ptsxclnkg0hsp9v83arc3gwndcwj64jj3ryd2sva0rxg
  - &machine_nas age1uxyppga3nlqwy4tjw3mv39r25d9klpjjrxa79la3hu25ra02sa7qwzw9m7
  - &user_aymerici age1qw932v4nt3muyy7lf6f2k68627huql68duzqvq7qq0tljr37cp6sjq07f9
  - &user_segator age1m4scguauntyz5zwu9n44jjqfzexaymr3jq4pu3ydfcfxe3gc2pfsfdx6ke
creation_rules:
  # common secrets for machines and users
  - path_regex: secrets/common/.+$
    key_groups:
    - age:
      - *machine_xps15
      - *machine_fury
      - *machine_nas
      - *user_aymerici
      - *user_segator

  # secrets for fury machine
  - path_regex: secrets/hosts/fury/.+$
    key_groups:
    - age:
      - *user_aymerici
      - *user_segator
      - *machine_fury
  # secrets for xps15 machine
  - path_regex: secrets/hosts/xps15/.+$
    key_groups:
    - age:
      - *user_aymerici
      - *machine_xps15
  # secrets for nas machine
  - path_regex: secrets/hosts/seganas/.+$
    key_groups:
    - age:
      - *user_segator
      - *user_aymerici
      - *machine_nas

  # secrets for aymerici user
  - path_regex: secrets/users/aymerici/.+$
    key_groups:
    - age:    
      - *user_segator
      - *user_aymerici
  # secrets for aymerici user
  - path_regex: secrets/users/segator/.+$
    key_groups:
    - age:
      - *user_segator