---
apiVersion: v1
kind: Namespace
metadata:
  name: dex
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dex-idp
  namespace: dex
spec:
  interval: 1h
  url: https://charts.dexidp.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 30m
  chart:
    spec:
      chart: dex
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: dex-idp
        namespace: dex
      interval: 1h
  values:
    config:
      # Set it to a valid URL
      issuer: http://dex.{base_domain}

      # See https://dexidp.io/docs/storage/ for more options
      storage:
        type: memory

      # Enable at least one connector
      # See https://dexidp.io/docs/connectors/ for more options
      enablePasswordDB: true

    ingress:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: acme

      hosts:
        - host: dex.{base_domain}
          paths:
            - path: /

      tls:
        - hosts:
            - dex.{base_domain}
          secretName: ingress-dex-cert