apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: ${cluster_secret_store_name}
  namespace: ${namespace}
spec:
  provider:
    oracle:
      vault: ${vault_id}
      region: ${region}
      auth:
        user: ${user_id}
        tenancy: ${tenancy_id}
        principalType: UserPrincipal
        secretRef:
          privatekey:
            name: ${vault_oci_secret_name}
            key: privateKey
            namespace: ${namespace}
          fingerprint:
            name: ${vault_oci_secret_name}
            key: fingerprint
            namespace: ${namespace}