user: ENC[AES256_GCM,data:hDNPqJKqJfh7a3H6JlruzhXs9jBHos0bMrWNxTK0K5yjgvXgJcLX14AMUx8yoAfobN70njwQrtEb9kvQJYRH+3I6j8EZKS/EyEXbzA==,iv:+xrvfxygW5Emqi4m9FzScfTjsHt8u8wLbYFG8L+UGsM=,tag:AtWW3Rw5iO+hI23ZNxz5Rg==,type:str]
fingerprint: ENC[AES256_GCM,data:AWPYZL88sJfUtocxsI+W7+YkLZZnHSFNvsG25fqTKSAt0FtILRPL4RTKTJCPk40=,iv:PyoqLbl8qWS2YwEhF00DVNkcV5yubAjL+Yqjrini3UE=,tag:8yDpkXWOA6V2fXrqn3S3iw==,type:str]
tenancy: ENC[AES256_GCM,data:wdnjVa2cgjoQjYoUyqumZ1rz30nyC1g3zaVw3VljEMXULOCycWW1xe73gos2C7J+Y0gP+tJta6j/XemLjwwXPqg86VAZ9LH3hsvMwIhFbg==,iv:LbyrqGg33wkZWFM0w69fZTsremoTpd2865n4/UDIrQk=,tag:68M2U7ao2rrQPxQ1kCi93A==,type:str]
region: ENC[AES256_GCM,data:b7DB5npytceDUg==,iv:evuu5SZ2cvDnCj9LcB33mcHj8OACRXmdXH5EHA2zYuQ=,tag:Jr7JkjBTskwF0HFTkxf3wA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m4scguauntyz5zwu9n44jjqfzexaymr3jq4pu3ydfcfxe3gc2pfsfdx6ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SEhaZllNTHVYeTQxM0lL
            WWhxVldTTEpVS1lqbVByWXNIdnpXV0VMZUZ3ClVIR3NGT2dyazhlM0V1SmhhN2Jl
            MzhSN21PV3hselVhVHNPZnNZaEJiKzAKLS0tIFNKSGtRbzU0RG5QcG9mQnkyQ3lq
            aXI0dDU2azlteXNPRW5Oc0FLajlkYWsKcoV4ifCxvn8HjXrD3+6z8Hi0O5sOYE6M
            ehZ4XVFdY2gH5+yYEjIbhYv+yp5O6it4tS1GX0FhnrDrzJ5LLH6+CQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qw932v4nt3muyy7lf6f2k68627huql68duzqvq7qq0tljr37cp6sjq07f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NzFtMURObHZJUC9uVVhH
            azI4aGJydTNlWXM0aktUTWVxeEFXV1NINFRrCjNFbytnVmhkbEhZK0ZUNWFHV1pX
            OGVZblk2TW1CNndjTGROa0VJdERyQkUKLS0tIE5UalEzcmhVK3lBbTdPVTJFUDkr
            Ri9XZG9TNW05Z0ZoaGJIVmE1Nm15NmcK1HjAQ6tpj+OQeK9EMHhcH43MNtBFA4jR
            ZfcLgeF6StGsko5orZykEiFhHCGlkwV3lpRDaV2ogFar3IGFwiZOwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-22T15:59:32Z"
    mac: ENC[AES256_GCM,data:UdQ+vZOiPVDD0A4c/mhcPDD6t+NOY8aqDw2GQG0gIAQc/8KwvlwTDT5G7kr1znDT4f8K8VIdAyLLXC5hFzNnpZlnuWL1/pFMUy+687jkor/rVeGl7i3xbKzbPqke23SnGI4zDwLhfByH3NjXfUvMbqH/pWgJ3dT+8j4VM4GaBAo=,iv:SmGXiWx2Dnia5r/fEhY84rncsw6r+Q02w0vKlQPlYuY=,tag:nBL2TyKw/67PICEkpvhY8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
