apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
spec:
  interval: 1h
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: "3.3.7"
      sourceRef:
        kind: HelmRepository
        name: kyverno
  interval: 1h
