proxmox:
    host: ENC[AES256_GCM,data:xMHcou0wealt1eAuRiXZt7bbcXO1jwBShEpl,iv:/JfkZpS210EfpnAEZs+SJjP8lFaqeYlGHyv8hFyaNYk=,tag:kl3Sr46eVKJmfrNdMZJmxg==,type:str]
    user: ENC[AES256_GCM,data:4j6EFrTsNK1DtYQo/22Qts2GmHnK/g==,iv:9RBUGAqzm3x3t8oD5em2tLaLv8hmLpjx6qqV1wI8psA=,tag:KdAUCjSdoEajnD0YQW5tmQ==,type:str]
    token: ENC[AES256_GCM,data:JB03AwGTn1t8+IEgAdwdpLcc8Jfot5TZ1HjZbX6AtFw08CFTnBbJGNuwY555gEp/XPBFE0YP1w1O564=,iv:2TZhp25E5W/2P0dKy0SPonwO4A5TVifwWkdcBgE0pXs=,tag:9K9XTJTtsm91p2Qt9kRfMA==,type:str]
aws:
    access_key: ENC[AES256_GCM,data:uh03x7HnmoYjr3QPiN7difeySNM=,iv:bd+niM7VTeG1c6PBJa07HhdbSqtvLwXKK/HDaPrwH4s=,tag:w0+CqiVl1pxLbSyoEtmVcw==,type:str]
    secret_access_key: ENC[AES256_GCM,data:vRAtGhZzxBH+ROa7u+iR+fgBUyPnnQZcXyN9DUVZcNh+8QPL6zU/rg==,iv:j7+aRypRxC01KIOFqw1hahuVKi4MOsSZi28NoS6TDjs=,tag:W/t+/3L608H82YK9ybn6+A==,type:str]
cloudflare:
    api_token: ENC[AES256_GCM,data:VcrzgJomvfS7nagAc0//pCSwy+eE7kw26pLKK0igKlUSI/0fDFSCBA==,iv:LtfQLINdBGFZVC6b1w+aoyhtHQ8NSw1pZTh99xgpeoA=,tag:Fr08ubu2L490rl2qfCZgnw==,type:str]
hetzner:
    api_token: ENC[AES256_GCM,data:ZZYX9kC9CHe14gUgMFrCsNJab9fchebkYre68NzvbDPDRSiGLOjA/01b4z7BrueZzqMZF35tcGxh7P9foIP5+A==,iv:DqtuYi88oSNlQE3Lo2jfpLP75r6y3vGLh8QgQQGQu64=,tag:u0kTwG+8I92VCekItlNRrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m4scguauntyz5zwu9n44jjqfzexaymr3jq4pu3ydfcfxe3gc2pfsfdx6ke
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc1U0bm5zTEhZZ1l1V1JO
            TGJrV2xKaERUcEQrZThxN3FHTjNIdEhBem5zClkrb1FmYllwNVpHY0UwR1lUL09a
            QmprdXRCVVQrTElhcWFOQTNSQSs5NDQKLS0tIFN5TmxqSkhlVW10R1VhUTBGMm8r
            WGRRV3dOeFIvSnBPYjZSQzFZNVBRS28KuI70F2uVg/FLCZQ8TFidWDKy/bQXN3wD
            BLtlxiHHM8m5J8GWqXPlren5nV5hEBodkSY62MJTjgWo7voyNA2eyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qw932v4nt3muyy7lf6f2k68627huql68duzqvq7qq0tljr37cp6sjq07f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcm1HblNJMGZibkJKQjBC
            WmpmM2dHVk93QVFkbEkwQzRMaTFiT1lWSUN3CnFQRmR1V1c5Y0ZjS3VsZVhZMFRC
            Sk13MFVjOFRqak1rTVZEOGpGWWVNVHcKLS0tIDBMQ0RXYU5aVXcxM1BwY09wRXlE
            b2lXRXAvb3hHUldYOHlXSTRmTk5kODgKSVJxVoGZ/FekcdKZ3qzLeak89ORGmOWk
            FldzPglZxEvNNUvFSskBhzcRKt8t+5/lhuCTugtlxReI8QtpB8SFUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-28T15:21:17Z"
    mac: ENC[AES256_GCM,data:SrseeHceQUYnpBvx7DTfB0twPN9mjiBUcl/gLbC7aPci/RGrbZnxHVpokEA+EXCXwRB/4yUYoIBZwbMrDWfPzLnO9D3Hy9KYKij32ZYJb2LRDuMXWbMZkOMozPbaMIiwGfKcxYKzKJ8r8/JOW/EDBEPlOT/42i/bU63QDNLr3qQ=,iv:IRfHAQUPw48YvXWhW97rz/ulBqXs4RhLxGeXvUbevkM=,tag:GfQWaqpL7IoohaCv3vrS5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
